### PR TITLE
defrianafandi/create hello world in python

### PR DESCRIPTION
**Pull request by defrianafandi**

### CODE REVIEW

**Review by ariefrahmansyah — CHANGES_REQUESTED** [review]
Hi, @defrianafandi 
Tolong file ini dimasukin ke folder kamu ya

**Review by ariefrahmansyah — APPROVED** [review]

**Review by ariefrahmansyah — CHANGES_REQUESTED** [review]
please rename the file ya :)
ekstensinya harus `.py`

**Review by ariefrahmansyah — APPROVED** [review]
awesome. thanks @defrianafandi

**Comment by defrianafandi** [comment]
@lloistborn kak, request review dong

**Review by Wentyocta — APPROVED** [review]

**Pull request merged**
